on:
  workflow_call:
    inputs:
      test_scheduler_manifest:
        default: "daemonset"
        type: string
      use_legacy:
        default: ""
        type: string

jobs:
  e2e-k8s:
    name: "e2e-k8s"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_versions: ["1.26.3", "1.25.8", "1.24.12"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
      TEST_SCHEDULER_MANIFEST: ${{ inputs.test_scheduler_manifest }}
      USE_LEGACY: ${{ inputs.use_legacy }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - uses: actions/cache/restore@v3
        with:
          path: |
            bin
            e2e/bin
            e2e/topolvm.img
          key: e2e-cache-${{ github.sha }}
      - run: touch e2e/topolvm.img # update timestamp not to rebuild image
      - run: make -C e2e start-lvmd
      - run: make -C e2e test
