name: "e2e-k8s"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - name: cache e2e sidecar binaries
        uses: actions/cache@v3
        with:
          path: |
            e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk') }}
          restore-keys: |
            e2e-sidecars-
      - run: make -C e2e setup
      - run: make -C e2e topolvm.img
      - uses: actions/cache/save@v3
        with:
          path: |
            bin
            e2e/bin
            e2e/topolvm.img
          key: e2e-cache-${{ github.sha }}

  default:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml

  scheduler-manifest:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      test_scheduler_manifest: "deployment"

  use-legacy:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      use_legacy: "true"
